# Generated by Django 2.2.3 on 2019-07-24 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.TextField()),
                ('date', models.DateTimeField()),
                ('inventory_level', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Data',
        ),
    ]
