# Generated by Django 2.2.3 on 2019-07-24 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0004_auto_20190724_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='date',
            field=models.DateField(),
        ),
    ]
