# Generated by Django 2.2.3 on 2019-07-24 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0006_auto_20190724_2202'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='date',
        ),
        migrations.RemoveField(
            model_name='products',
            name='inventory_level',
        ),
        migrations.CreateModel(
            name='inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('inventory_level', models.IntegerField()),
                ('products', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ravi.Products')),
            ],
        ),
    ]
