# Generated by Django 2.2.3 on 2019-07-25 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ravi', '0007_auto_20190724_2219'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='product_name',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
